[api]
host = "127.0.0.1"
port = 5000
debug = true

[db]
host = "localhost"
port = 5432
database = "image_service"
user = "postgres"
password = "2685118"
echo = true


[logging]
level = "DEBUG"
render_json_logs = false
#path = "./logs/logs.log"
